name: 'get-release-tag'
description: 'Gets the release tag version to be used in actions'
author: 'dusmartijngames'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'heart'
  color: 'red'

# Define your outputs here.
outputs:
  version:
    description: "Version number parsed from GitHub release tag name"

runs:
  using: node20
  main: dist/index.js
